// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: donations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAnonymousDonation = `-- name: CreateAnonymousDonation :one
INSERT INTO donations (
  goal_id,
  amount,
  currency,
  is_anonymous
) VALUES (
  $1, $2, $3, TRUE
) RETURNING id, user_id, goal_id, amount, currency, is_anonymous, created_at
`

type CreateAnonymousDonationParams struct {
	GoalID   int64  `json:"goal_id"`
	Amount   int64  `json:"amount"`
	Currency string `json:"currency"`
}

func (q *Queries) CreateAnonymousDonation(ctx context.Context, arg CreateAnonymousDonationParams) (Donation, error) {
	row := q.db.QueryRow(ctx, createAnonymousDonation, arg.GoalID, arg.Amount, arg.Currency)
	var i Donation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GoalID,
		&i.Amount,
		&i.Currency,
		&i.IsAnonymous,
		&i.CreatedAt,
	)
	return i, err
}

const createDonation = `-- name: CreateDonation :one
INSERT INTO donations (
  user_id,
  goal_id,
  amount,
  currency,
  is_anonymous
) VALUES (
  $1, $2, $3, $4, $5
) RETURNING id, user_id, goal_id, amount, currency, is_anonymous, created_at
`

type CreateDonationParams struct {
	UserID      pgtype.Int8 `json:"user_id"`
	GoalID      int64       `json:"goal_id"`
	Amount      int64       `json:"amount"`
	Currency    string      `json:"currency"`
	IsAnonymous bool        `json:"is_anonymous"`
}

func (q *Queries) CreateDonation(ctx context.Context, arg CreateDonationParams) (Donation, error) {
	row := q.db.QueryRow(ctx, createDonation,
		arg.UserID,
		arg.GoalID,
		arg.Amount,
		arg.Currency,
		arg.IsAnonymous,
	)
	var i Donation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GoalID,
		&i.Amount,
		&i.Currency,
		&i.IsAnonymous,
		&i.CreatedAt,
	)
	return i, err
}

const getDonation = `-- name: GetDonation :one
SELECT id, user_id, goal_id, amount, currency, is_anonymous, created_at FROM donations
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDonation(ctx context.Context, id int64) (Donation, error) {
	row := q.db.QueryRow(ctx, getDonation, id)
	var i Donation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GoalID,
		&i.Amount,
		&i.Currency,
		&i.IsAnonymous,
		&i.CreatedAt,
	)
	return i, err
}

const listDonationsByGoal = `-- name: ListDonationsByGoal :many
SELECT id, user_id, goal_id, amount, currency, is_anonymous, created_at FROM donations
WHERE goal_id = $1
ORDER BY created_at DESC
LIMIT $2
OFFSET $3
`

type ListDonationsByGoalParams struct {
	GoalID int64 `json:"goal_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListDonationsByGoal(ctx context.Context, arg ListDonationsByGoalParams) ([]Donation, error) {
	rows, err := q.db.Query(ctx, listDonationsByGoal, arg.GoalID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Donation{}
	for rows.Next() {
		var i Donation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GoalID,
			&i.Amount,
			&i.Currency,
			&i.IsAnonymous,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDonationsByUser = `-- name: ListDonationsByUser :many
SELECT id, user_id, goal_id, amount, currency, is_anonymous, created_at FROM donations
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
OFFSET $3
`

type ListDonationsByUserParams struct {
	UserID pgtype.Int8 `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListDonationsByUser(ctx context.Context, arg ListDonationsByUserParams) ([]Donation, error) {
	rows, err := q.db.Query(ctx, listDonationsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Donation{}
	for rows.Next() {
		var i Donation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GoalID,
			&i.Amount,
			&i.Currency,
			&i.IsAnonymous,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
