// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: goals.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGoal = `-- name: CreateGoal :one
INSERT INTO goals (
  title,
  description,
  target_amount
) VALUES (
  $1, $2, $3
) RETURNING id, title, description, target_amount, collected_amount, is_active, created_at
`

type CreateGoalParams struct {
	Title        string      `json:"title"`
	Description  pgtype.Text `json:"description"`
	TargetAmount pgtype.Int8 `json:"target_amount"`
}

func (q *Queries) CreateGoal(ctx context.Context, arg CreateGoalParams) (Goal, error) {
	row := q.db.QueryRow(ctx, createGoal, arg.Title, arg.Description, arg.TargetAmount)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.TargetAmount,
		&i.CollectedAmount,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getGoal = `-- name: GetGoal :one
SELECT id, title, description, target_amount, collected_amount, is_active, created_at FROM goals
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetGoal(ctx context.Context, id int64) (Goal, error) {
	row := q.db.QueryRow(ctx, getGoal, id)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.TargetAmount,
		&i.CollectedAmount,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveGoals = `-- name: ListActiveGoals :many
SELECT id, title, description, target_amount, collected_amount, is_active, created_at FROM goals
WHERE is_active = true
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListActiveGoalsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListActiveGoals(ctx context.Context, arg ListActiveGoalsParams) ([]Goal, error) {
	rows, err := q.db.Query(ctx, listActiveGoals, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Goal{}
	for rows.Next() {
		var i Goal
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.TargetAmount,
			&i.CollectedAmount,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoals = `-- name: ListGoals :many
SELECT id, title, description, target_amount, collected_amount, is_active, created_at FROM goals
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListGoalsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListGoals(ctx context.Context, arg ListGoalsParams) ([]Goal, error) {
	rows, err := q.db.Query(ctx, listGoals, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Goal{}
	for rows.Next() {
		var i Goal
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.TargetAmount,
			&i.CollectedAmount,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGoal = `-- name: UpdateGoal :one
UPDATE goals
SET
  title = COALESCE($1, title),
  description = COALESCE($2, description),
  target_amount = COALESCE($3, target_amount),
  is_active = COALESCE($4, is_active)
WHERE id = $5
RETURNING id, title, description, target_amount, collected_amount, is_active, created_at
`

type UpdateGoalParams struct {
	Title        pgtype.Text `json:"title"`
	Description  pgtype.Text `json:"description"`
	TargetAmount pgtype.Int8 `json:"target_amount"`
	IsActive     pgtype.Bool `json:"is_active"`
	ID           int64       `json:"id"`
}

func (q *Queries) UpdateGoal(ctx context.Context, arg UpdateGoalParams) (Goal, error) {
	row := q.db.QueryRow(ctx, updateGoal,
		arg.Title,
		arg.Description,
		arg.TargetAmount,
		arg.IsActive,
		arg.ID,
	)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.TargetAmount,
		&i.CollectedAmount,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
