// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddToGoalCollectedAmount(ctx context.Context, arg AddToGoalCollectedAmountParams) (Goal, error)
	CreateAnonymousDonation(ctx context.Context, arg CreateAnonymousDonationParams) (Donation, error)
	CreateDonation(ctx context.Context, arg CreateDonationParams) (Donation, error)
	CreateGoal(ctx context.Context, arg CreateGoalParams) (Goal, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetDonation(ctx context.Context, id int64) (Donation, error)
	GetGoal(ctx context.Context, id int64) (Goal, error)
	GetGoalForUpdate(ctx context.Context, id int64) (Goal, error)
	GetGoalTotalDonations(ctx context.Context, goalID int64) (interface{}, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserTotalDonations(ctx context.Context, userID pgtype.Int8) (interface{}, error)
	ListActiveGoals(ctx context.Context, arg ListActiveGoalsParams) ([]Goal, error)
	ListDonationsByGoal(ctx context.Context, arg ListDonationsByGoalParams) ([]Donation, error)
	ListDonationsByUser(ctx context.Context, arg ListDonationsByUserParams) ([]Donation, error)
	ListGoalDonors(ctx context.Context, arg ListGoalDonorsParams) ([]User, error)
	ListGoals(ctx context.Context, arg ListGoalsParams) ([]Goal, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateGoal(ctx context.Context, arg UpdateGoalParams) (Goal, error)
}

var _ Querier = (*Queries)(nil)
