// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transfer.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getGoalTotalDonations = `-- name: GetGoalTotalDonations :one
SELECT COALESCE(SUM(amount), 0) AS total_amount
FROM donations
WHERE goal_id = $1
`

func (q *Queries) GetGoalTotalDonations(ctx context.Context, goalID int64) (interface{}, error) {
	row := q.db.QueryRow(ctx, getGoalTotalDonations, goalID)
	var total_amount interface{}
	err := row.Scan(&total_amount)
	return total_amount, err
}

const getUserTotalDonations = `-- name: GetUserTotalDonations :one
SELECT COALESCE(SUM(amount), 0) AS total_amount
FROM donations
WHERE user_id = $1
`

func (q *Queries) GetUserTotalDonations(ctx context.Context, userID pgtype.Int8) (interface{}, error) {
	row := q.db.QueryRow(ctx, getUserTotalDonations, userID)
	var total_amount interface{}
	err := row.Scan(&total_amount)
	return total_amount, err
}

const listGoalDonors = `-- name: ListGoalDonors :many
SELECT u.id, u.email, u.name, u.password, u.created_at
FROM users u
JOIN donations d ON d.user_id = u.id
WHERE d.goal_id = $1
GROUP BY u.id
ORDER BY u.id
LIMIT $2
OFFSET $3
`

type ListGoalDonorsParams struct {
	GoalID int64 `json:"goal_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListGoalDonors(ctx context.Context, arg ListGoalDonorsParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listGoalDonors, arg.GoalID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Password,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
